package com.conductor.shared.customer;

public enum TimelineEventType {
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    CUSTOMER_MERGED,
    CUSTOMER_DELETED,
    CUSTOMER_ARCHIVED,
    MESSAGE_SENT,
    MESSAGE_RECEIVED,
    WORKFLOW_EXECUTED,
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    TAG_ASSIGNED,
    TAG_REMOVED,
    SEGMENT_ASSIGNED,
    SEGMENT_REMOVED,
    CONTACT_ADDED,
    CONTACT_UPDATED,
    CONTACT_REMOVED,
    PREFERENCE_UPDATED,
    ATTRIBUTE_UPDATED,
    INTEGRATION_ACTIVITY,
    PROFILE_UPDATED
}
